sudo: true
cache:
  bundler: true
  directories:
  - cache/
notifications:
  email: false
language: c
compiler: gcc
env:
  global:
    - OPENWRT_VERSION=trunk
    - PACKAGES="cyassl n2n-v2 wolfmqtt"
  matrix:
    - TARGET=ar71xx SUBTARGET=generic
    - TARGET=ramips SUBTARGET=mt7620
    - TARGET=ramips SUBTARGET=mt7621
install:
- mkdir -p $TRAVIS_BUILD_DIR/local ; cd $TRAVIS_BUILD_DIR/local
- wget "http://us.archive.ubuntu.com/ubuntu/pool/main/c/ccache/ccache_3.1.6-1_amd64.deb"
- dpkg -x *.deb .
- mkdir -p $TRAVIS_BUILD_DIR/cache ; cd $TRAVIS_BUILD_DIR/cache
- export SDK_URL=https://downloads.openwrt.org/snapshots/$OPENWRT_VERSION/$TARGET/$SUBTARGET/OpenWrt-SDK-$TARGET-${SUBTARGET}_gcc-5.3.0_musl-1.1.14.Linux-x86_64.tar.bz2
- wget -c $SDK_URL
- mkdir -p $TRAVIS_BUILD_DIR/sdk ; cd $TRAVIS_BUILD_DIR/sdk
- export FILE=$TRAVIS_BUILD_DIR/cache/$(basename $SDK_URL)
- file $FILE
- tar xjf $FILE
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- for PACKAGE in $PACKAGES ; do ln -sfv $TRAVIS_BUILD_DIR/$PACKAGE package/ ; done
script:
- export PATH=$TRAVIS_BUILD_DIR/local/usr/bin:$PATH
- cd $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*
- make V=s
- find $TRAVIS_BUILD_DIR/sdk/OpenWrt-SDK-*/bin/
- find . -name *.ipk -exec cp {} $TRAVIS_BUILD_DIR \;
- cd $TRAVIS_BUILD_DIR/
before_deploy:
  git fetch --tags
deploy:
  provider: releases
  api_key:
    secure: Cr58ghbr6FMTZLkFxGea9mKocIDrTMfyGH4kBfBOa7rEH5/f/ccW58qz7JUH3xih/jd95HrHaFhQFWAmdkVzwfMa80pf/PHKuWFZ913LEw34LExzyKXLGWvajb95mNnU8L91U4xsa/9hYup5cQvISfZkmtZcHw89ce4WwPPsX/o=
  skip_cleanup: true
  file_glob: true
  file: $TRAVIS_BUILD_DIR/*.ipk
  on:
    tags: true
    all_branches: true
